apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xpapibackend-trigger-crt
spec:
  commonName: xpapibackend.trigger.privapps.nttscloud.com
  dnsNames:
    - xpapibackend.trigger.privapps.nttscloud.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: xpapibackend-trigger-tls-secret
